//! Typed semantic transactions and ephemeral undo/redo history.
//!
//! [`ProjectSession`] is the application-facing mutation boundary for the R2
//! project core. It owns session revision and history state while keeping the
//! canonical [`Project`] free of editor/session concerns. Every preview and
//! commit evaluates the same typed commands against an isolated project copy;
//! only a successful commit adopts that copy.

use std::fmt::{Display, Formatter};

use street_concept_designer_kernel::{
    JunctionCandidate, JunctionId, KernelError, LaneConnection, RegenerationResult, Road,
    RoadNetwork, TolerancePolicy,
};
use street_concept_designer_project_core::{
    Project, ProjectError, Scenario, ScenarioId, ScenarioRole,
};

/// Caller-supplied stable identity for one transaction.
///
/// Transaction ids are intentionally not generated by this crate. They are
/// deterministic, non-empty, and follow the existing semantic-id convention
/// that whitespace is invalid.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct TransactionId(String);

impl TransactionId {
    /// Construct a valid caller-supplied transaction identity.
    pub fn new(value: impl Into<String>) -> Result<Self, SessionError> {
        let value = value.into();
        if value.is_empty() || value.chars().any(char::is_whitespace) {
            return Err(SessionError::InvalidTransactionId);
        }
        Ok(Self(value))
    }

    /// Borrow the stable identity text.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl AsRef<str> for TransactionId {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl Display for TransactionId {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// The bounded typed command inventory implemented by R2C.
#[derive(Debug, Clone, PartialEq)]
pub enum Command {
    /// Add a complete validated scenario to the project.
    AddScenario { scenario: Scenario },
    /// Duplicate a scenario while explicitly choosing the new metadata.
    DuplicateScenario {
        source_scenario_id: ScenarioId,
        new_scenario_id: ScenarioId,
        new_name: String,
        role: ScenarioRole,
        locked: bool,
    },
    /// Rename one scenario in its explicit project scope.
    RenameScenario {
        scenario_id: ScenarioId,
        new_name: String,
    },
    /// Explicitly change a scenario's lock state.
    SetScenarioLock {
        scenario_id: ScenarioId,
        locked: bool,
    },
    /// Add one complete semantic road to a scenario.
    AddRoad { scenario_id: ScenarioId, road: Road },
    /// Replace one semantic road and regenerate its affected junctions.
    ReplaceRoad { scenario_id: ScenarioId, road: Road },
    /// Promote a current candidate to an explicit junction in one scenario.
    CreateJunctionFromCandidate {
        scenario_id: ScenarioId,
        candidate: JunctionCandidate,
        junction_id: JunctionId,
        options: street_concept_designer_kernel::JunctionOptions,
    },
    /// Set one authored corner radius through the kernel API.
    SetCornerRadius {
        scenario_id: ScenarioId,
        junction_id: JunctionId,
        corner_id: street_concept_designer_kernel::CornerId,
        radius_m: f64,
    },
    /// Replace the complete authored manual lane-connectivity set.
    ReplaceLaneConnections {
        scenario_id: ScenarioId,
        junction_id: JunctionId,
        connections: Vec<LaneConnection>,
    },
}

/// One caller-supplied transaction evaluated in deterministic command order.
#[derive(Debug, Clone, PartialEq)]
pub struct Transaction {
    id: TransactionId,
    expected_revision: u64,
    summary: String,
    commands: Vec<Command>,
}

impl Transaction {
    /// Construct a non-empty transaction with a meaningful summary.
    pub fn new(
        id: TransactionId,
        expected_revision: u64,
        summary: impl Into<String>,
        commands: Vec<Command>,
    ) -> Result<Self, SessionError> {
        if commands.is_empty() {
            return Err(SessionError::EmptyTransaction);
        }
        let summary = summary.into();
        if summary.trim().is_empty() {
            return Err(SessionError::InvalidTransactionSummary);
        }
        Ok(Self {
            id,
            expected_revision,
            summary: summary.trim().to_owned(),
            commands,
        })
    }

    /// Stable caller-supplied transaction identity.
    pub fn id(&self) -> &TransactionId {
        &self.id
    }

    /// Session revision against which this proposal was created.
    pub fn expected_revision(&self) -> u64 {
        self.expected_revision
    }

    /// Human-readable transaction-level intent.
    pub fn summary(&self) -> &str {
        &self.summary
    }

    /// Commands in the exact deterministic application order.
    pub fn commands(&self) -> &[Command] {
        &self.commands
    }
}

/// Public metadata for one committed human-level history item.
///
/// Project snapshots remain private implementation state. This type exposes
/// only the stable transaction identity and human-readable summary.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HistoryItem {
    transaction_id: TransactionId,
    summary: String,
}

impl HistoryItem {
    /// Transaction identity retained in history.
    pub fn transaction_id(&self) -> &TransactionId {
        &self.transaction_id
    }

    /// Human-readable transaction summary retained in history.
    pub fn summary(&self) -> &str {
        &self.summary
    }
}

/// Result of evaluating a transaction without mutating the session.
#[derive(Debug, Clone, PartialEq)]
pub struct PreviewResult {
    candidate_project: Project,
    history_item: HistoryItem,
}

impl PreviewResult {
    /// Borrow the isolated candidate project.
    pub fn candidate_project(&self) -> &Project {
        &self.candidate_project
    }

    /// Alias for callers that treat a preview as a project result.
    pub fn project(&self) -> &Project {
        self.candidate_project()
    }

    /// Consume the result and return the candidate project.
    pub fn into_candidate_project(self) -> Project {
        self.candidate_project
    }

    /// Transaction identity associated with this preview.
    pub fn transaction_id(&self) -> &TransactionId {
        self.history_item.transaction_id()
    }

    /// Transaction summary associated with this preview.
    pub fn summary(&self) -> &str {
        self.history_item.summary()
    }
}

/// Errors produced by transaction construction and session history control.
#[derive(Debug, Clone, PartialEq)]
pub enum SessionError {
    /// A transaction id was empty or contained whitespace.
    InvalidTransactionId,
    /// A transaction contained no commands.
    EmptyTransaction,
    /// A transaction summary was empty or whitespace-only.
    InvalidTransactionSummary,
    /// The proposal or history operation targeted a different revision.
    StaleRevision {
        expected_revision: u64,
        current_revision: u64,
    },
    /// Advancing the monotonic session revision would overflow `u64`.
    RevisionOverflow,
    /// No committed transaction is available to undo.
    NoUndoAvailable,
    /// No undone transaction is available to redo.
    NoRedoAvailable,
    /// A valid transaction produced a project identical to the current one.
    NoOpTransaction,
    /// The project-domain layer rejected the operation.
    Project(ProjectError),
    /// The engineering kernel rejected the operation.
    Kernel(KernelError),
}

impl Display for SessionError {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidTransactionId => f.write_str("invalid transaction id"),
            Self::EmptyTransaction => f.write_str("transaction has no commands"),
            Self::InvalidTransactionSummary => f.write_str("invalid transaction summary"),
            Self::StaleRevision {
                expected_revision,
                current_revision,
            } => write!(
                f,
                "stale revision: expected {expected_revision}, current {current_revision}"
            ),
            Self::RevisionOverflow => f.write_str("session revision overflow"),
            Self::NoUndoAvailable => f.write_str("no undo available"),
            Self::NoRedoAvailable => f.write_str("no redo available"),
            Self::NoOpTransaction => f.write_str("transaction has no semantic effect"),
            Self::Project(error) => Display::fmt(error, f),
            Self::Kernel(error) => Display::fmt(error, f),
        }
    }
}

impl std::error::Error for SessionError {}

impl From<ProjectError> for SessionError {
    fn from(error: ProjectError) -> Self {
        Self::Project(error)
    }
}

impl From<KernelError> for SessionError {
    fn from(error: KernelError) -> Self {
        Self::Kernel(error)
    }
}

#[derive(Debug, Clone)]
struct HistoryEntry {
    item: HistoryItem,
    before: Project,
    after: Project,
}

#[derive(Debug)]
struct EvaluatedTransaction {
    candidate: Project,
    item: HistoryItem,
}

/// Canonical project plus ephemeral revision and snapshot history.
///
/// The session deliberately exposes no mutable `Project`, `Scenario`, or
/// `RoadNetwork` reference. The only mutation path is a typed transaction,
/// and undo/redo restore private semantic snapshots without re-running command
/// or external logic.
pub struct ProjectSession {
    project: Project,
    revision: u64,
    undo_stack: Vec<HistoryEntry>,
    redo_stack: Vec<HistoryEntry>,
}

impl ProjectSession {
    /// Validate the initial project with the accepted default policy.
    pub fn new(project: Project) -> Result<Self, SessionError> {
        project.validate_default()?;
        Ok(Self {
            project,
            revision: 0,
            undo_stack: Vec::new(),
            redo_stack: Vec::new(),
        })
    }

    /// Borrow the canonical project without exposing mutation.
    pub fn project(&self) -> &Project {
        &self.project
    }

    /// Current monotonic session revision.
    pub fn revision(&self) -> u64 {
        self.revision
    }

    /// Metadata for committed undo items, oldest first.
    pub fn undo_history(&self) -> Vec<HistoryItem> {
        self.undo_stack
            .iter()
            .map(|entry| entry.item.clone())
            .collect()
    }

    /// Metadata for available redo items, next redo operation first.
    pub fn redo_history(&self) -> Vec<HistoryItem> {
        self.redo_stack
            .iter()
            .rev()
            .map(|entry| entry.item.clone())
            .collect()
    }

    /// Evaluate a transaction against an isolated candidate project.
    pub fn preview(&self, transaction: &Transaction) -> Result<PreviewResult, SessionError> {
        let evaluated = self.evaluate_transaction(transaction)?;
        Ok(PreviewResult {
            candidate_project: evaluated.candidate,
            history_item: evaluated.item,
        })
    }

    /// Evaluate and atomically commit one transaction as one history item.
    pub fn commit(&mut self, transaction: &Transaction) -> Result<HistoryItem, SessionError> {
        let evaluated = self.evaluate_transaction(transaction)?;
        let next_revision = next_revision(self.revision)?;
        let before = self.project.clone();
        let item = evaluated.item;
        self.project = evaluated.candidate;
        self.revision = next_revision;
        self.undo_stack.push(HistoryEntry {
            item: item.clone(),
            before,
            after: self.project.clone(),
        });
        self.redo_stack.clear();
        Ok(item)
    }

    /// Restore the last committed project snapshot and advance revision.
    pub fn undo(&mut self, expected_revision: u64) -> Result<HistoryItem, SessionError> {
        ensure_revision(expected_revision, self.revision)?;
        let next_revision = next_revision(self.revision)?;
        let entry = self.undo_stack.pop().ok_or(SessionError::NoUndoAvailable)?;
        let item = entry.item.clone();
        self.project = entry.before.clone();
        self.revision = next_revision;
        self.redo_stack.push(entry);
        Ok(item)
    }

    /// Restore the stored post-commit snapshot and advance revision.
    pub fn redo(&mut self, expected_revision: u64) -> Result<HistoryItem, SessionError> {
        ensure_revision(expected_revision, self.revision)?;
        let next_revision = next_revision(self.revision)?;
        let entry = self.redo_stack.pop().ok_or(SessionError::NoRedoAvailable)?;
        let item = entry.item.clone();
        self.project = entry.after.clone();
        self.revision = next_revision;
        self.undo_stack.push(entry);
        Ok(item)
    }

    fn evaluate_transaction(
        &self,
        transaction: &Transaction,
    ) -> Result<EvaluatedTransaction, SessionError> {
        ensure_revision(transaction.expected_revision, self.revision)?;
        let mut candidate = self.project.clone();
        for command in transaction.commands() {
            apply_command(&mut candidate, command)?;
        }
        candidate.validate_default()?;
        if candidate == self.project {
            return Err(SessionError::NoOpTransaction);
        }
        Ok(EvaluatedTransaction {
            candidate,
            item: HistoryItem {
                transaction_id: transaction.id.clone(),
                summary: transaction.summary.clone(),
            },
        })
    }
}

fn ensure_revision(expected_revision: u64, current_revision: u64) -> Result<(), SessionError> {
    if expected_revision != current_revision {
        return Err(SessionError::StaleRevision {
            expected_revision,
            current_revision,
        });
    }
    Ok(())
}

fn next_revision(current_revision: u64) -> Result<u64, SessionError> {
    current_revision
        .checked_add(1)
        .ok_or(SessionError::RevisionOverflow)
}

fn apply_command(project: &mut Project, command: &Command) -> Result<(), SessionError> {
    match command {
        Command::AddScenario { scenario } => {
            project.add_scenario(scenario.clone())?;
        }
        Command::DuplicateScenario {
            source_scenario_id,
            new_scenario_id,
            new_name,
            role,
            locked,
        } => {
            project.duplicate_scenario(
                source_scenario_id,
                new_scenario_id.clone(),
                new_name.clone(),
                *role,
                *locked,
            )?;
        }
        Command::RenameScenario {
            scenario_id,
            new_name,
        } => {
            project.rename_scenario(scenario_id, new_name.clone())?;
        }
        Command::SetScenarioLock {
            scenario_id,
            locked,
        } => {
            project.set_scenario_locked(scenario_id, *locked)?;
        }
        Command::AddRoad { scenario_id, road } => {
            let mut network = editable_network(project, scenario_id)?;
            network.add_road(road.clone())?;
            replace_network(project, scenario_id, network)?;
        }
        Command::ReplaceRoad { scenario_id, road } => {
            let mut network = editable_network(project, scenario_id)?;
            let affected_junction_ids = network
                .junctions()
                .iter()
                .filter(|junction| junction.road_ids().iter().any(|id| id == road.id()))
                .map(|junction| junction.id().clone())
                .collect::<Vec<_>>();
            network.replace_road(road.clone())?;
            let policy = TolerancePolicy::default();
            for junction_id in affected_junction_ids {
                match network.regenerate_junction(&junction_id, &policy)? {
                    RegenerationResult::Regenerated
                    | RegenerationResult::ManualConnectivityIncompatible
                    | RegenerationResult::Stale => {}
                }
            }
            replace_network(project, scenario_id, network)?;
        }
        Command::CreateJunctionFromCandidate {
            scenario_id,
            candidate,
            junction_id,
            options,
        } => {
            let mut network = editable_network(project, scenario_id)?;
            network.create_junction(
                candidate,
                junction_id.as_str(),
                options.clone(),
                &TolerancePolicy::default(),
            )?;
            replace_network(project, scenario_id, network)?;
        }
        Command::SetCornerRadius {
            scenario_id,
            junction_id,
            corner_id,
            radius_m,
        } => {
            let mut network = editable_network(project, scenario_id)?;
            network
                .junction_mut(junction_id)
                .ok_or(KernelError::MissingJunction)?
                .set_corner_radius(corner_id, *radius_m, &TolerancePolicy::default())?;
            replace_network(project, scenario_id, network)?;
        }
        Command::ReplaceLaneConnections {
            scenario_id,
            junction_id,
            connections,
        } => {
            let mut network = editable_network(project, scenario_id)?;
            network
                .junction_mut(junction_id)
                .ok_or(KernelError::MissingJunction)?
                .replace_lane_connections(connections.clone())?;
            replace_network(project, scenario_id, network)?;
        }
    }
    Ok(())
}

fn editable_network(
    project: &Project,
    scenario_id: &ScenarioId,
) -> Result<RoadNetwork, SessionError> {
    let scenario = project
        .scenario(scenario_id)
        .ok_or(ProjectError::MissingScenario)?;
    if scenario.is_locked() {
        return Err(ProjectError::ScenarioLocked.into());
    }
    Ok(scenario.network().clone())
}

fn replace_network(
    project: &mut Project,
    scenario_id: &ScenarioId,
    network: RoadNetwork,
) -> Result<(), SessionError> {
    project.replace_scenario_network(scenario_id, network, &TolerancePolicy::default())?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::next_revision;

    #[test]
    fn next_revision_uses_checked_arithmetic() {
        assert_eq!(next_revision(0).expect("zero increments"), 1);
        assert_eq!(
            next_revision(u64::MAX - 1).expect("maximum valid increment"),
            u64::MAX
        );
        assert!(next_revision(u64::MAX).is_err());
    }
}
